### ISSUE TITLE
enable tls version enum internally when using `-cipher-enum` flag

### ISSUE THREAD

**Issue by noraj** [projectdiscovery/tlsx#164]
### tlsx version:

v1.0.4

### Current Behavior:

```
$ tlsx -u example.org -cipher-enum
...                                                                                                                                                                                
example.org:443                                                                                                                                                                                                      
[INF] Connections made using crypto/tls: 1, zcrypto/tls: 0, openssl: 0

$ tlsx -u example.org -cipher-enum -sm openssl
...
example.org:443

$ tlsx -u example.org -cipher-enum -sm openssl -cipher
...
example.org:443 []

$ tlsx -u example.org -cipher-enum -sm ztls
...
example.org:443

$ tlsx -u example.org -cipher-enum -sm ctls
...
example.org:443
```

### Expected Behavior:

enumerate and display supported cipher

### Steps To Reproduce:

cf. current behavior

### Anything else:

Same behavior whatever the host is. Version enumeration is working.

**Comment by tarunKoyalwar** [comment]
- fixed in PR  #163

**Comment by tarunKoyalwar** [comment]
`-cipher-enum` requires `-version-enum` since cipher enumeration is done based on tls version .
 currently if `cipher-enum`  is not done if `-version-enum` flag is missing .

I guess `cipher-enum` should internally do version-enum without explicitly passing the flag

**Comment by noraj** [comment]
Sure, I thought I tested with both too.

**Comment by tarunKoyalwar** [comment]
@noraj , you should be able to use it in next release . there was minor issue in #163  and others which will be resolved shortly

**Comment by noraj** [comment]
> @noraj `-cipher-enum` requires `-version-enum` since cipher enumeration is done based on tls version . currently if `cipher-enum` is not done if `-version-enum` flag is missing .
> 
> I guess `cipher-enum` should internally do version-enum without explicitly passing the flag

I was going to say even when you use both flag you see nothing:

```
$ tlsx -u pwn.by -cipher-enum -version-enum     
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\  v1.0.4

                projectdiscovery.io

pwn.by:443 [tls13,tls12]
[INF] Connections made using crypto/tls: 34, zcrypto/tls: 3, openssl: 341
```

Because originally I was using both flag but I see in #168 it was outputting only on JSON output and not on STDOUT. So this should be good for 1.0.5.

**Comment by ehsandeep** [comment]
@noraj should be fixed now with the latest release.
