### ISSUE TITLE
Stuck when too many hostnames

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/tlsx#259]
Hi,
I'm using `TLSX v1.0.9` and I noticed that the tool gets stuck when a list with too many hostnames is used.

In my case, I used a file with 6000 hostnames, I stopped the execution after 7 hours because the tool was blocked (I ran in verbose mode, nothing was displayed in the output).

I use the following command :
```
tlsx -l hostnames.txt -san -silent -json
```

Let me know if more informations is needed

Regards

**Comment by ehsandeep** [comment]
@JoshuaMart, it was fixed in the latest release with https://github.com/projectdiscovery/tlsx/pull/284; the tool was getting stuck in a specific edge case.
