### ISSUE TITLE
False positive with untrusted flag, but manual certificate check shows trusted status

### ISSUE THREAD

**Issue by whydee86** [projectdiscovery/tlsx#268]
### Current Behavior:
In my case, the tool flagged a certificate as untrusted, but the manual inspection of the certificate showed it to be trusted. 

### Expected Behavior:
The tlsx tool should accurately identify untrusted certificates, providing reliable results consistent with manual certificate checks.

### Steps To Reproduce:
1. Run tlsx tool with the appropriate parameters on the target website. (tlsx -un -host ebay.co.jp)
2. Note the output and observe if any untrusted flags are raised.
3. Manually check the certificate of the website using other methods (e.g., web browser)

#### List of Certificates:
(https://ebay.co.jp/): The tlsx tool flagged the certificate as untrusted, but manual inspection showed it to be trusted.
(https://www.mylandscapes.co.uk/): Similarly, the tool indicated an untrusted certificate, while manual inspection confirmed its trustworthiness.
(https://comicon.it/): Another instance where the tool's untrusted flag did not match the actual trusted status of the certificate.  

#### More Certificates for example:
![image](https://github.com/projectdiscovery/tlsx/assets/43274863/d0449dde-8ae8-4f29-96eb-f9aa3394db0c)

I believe this issue is worth investigating to ensure the accuracy of the tlsx tool's results.

**Comment by ehsandeep** [comment]
@whydee86 this is now fixed in latest release - https://github.com/projectdiscovery/tlsx/releases/tag/v1.1.1

**Comment by whydee86** [comment]
I appreciate your attention and resolution to this issue. 
It's working amazing now, as you can see in the image below. Thank you!
![image](https://github.com/projectdiscovery/tlsx/assets/43274863/b121d1dc-7d6c-4908-8f36-1d8a9c43e05e)
