### ISSUE TITLE
support for multiple input with `-cipher-type` option

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/tlsx#306]
### Please describe your feature request:
Current support:

```
echo google.com | tlsx -ce -ct insecure
``` 

Expected support:

```
echo google.com | tlsx -ce -ct insecure,weak
```

currently it's limited to using one value at a time.

**Comment by dogancanbakir** [comment]
Depends on [#127](https://github.com/projectdiscovery/goflags/issues/127)
