### ISSUE TITLE
can not get cn info

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/tlsx#401]
$ tlsx -u 17.57.144.120 -cn -j -p 443        
```  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.1.5

		projectdiscovery.io

[INF] Current tlsx version v1.1.5 (latest)
[INF] Connections made using crypto/tls: 0, zcrypto/tls: 0, openssl: 0
```
but

$ openssl s_client -connect 17.57.144.120:443 2>/dev/null|grep 'subject='|grep "CN = "|grep ', O = '|grep ', ST ='|sed 's/.*CN = //g'
```
courier.push.apple.com
```
can get cn:courier.push.apple.com

what happened

**Comment by hexagr** [comment]
As a workaround until I can understand why the default scan isn't working, try using the `pre-handshake` (early termination) option. This should return the `cn` name and be faster than regular scanning. `tlsx -u 17.57.144.120 -pre-handshake -cn`

Not to "it works on my machine" you, but for me, this outputs `17.57.144.120:443 [courier.push.apple.com]"` 

It seems like maybe ztls handles the connection differently. This should work for servers up till TLS v1.3. See the note here: https://github.com/projectdiscovery/tlsx?tab=readme-ov-file#pre-handshake-early-termination
