### ISSUE TITLE
Add support for detecting whether a server requires clients to authenticate using a client certificate

### ISSUE THREAD

**Issue by mark-adams** [projectdiscovery/tlsx#564]
### Please describe your feature request:
I would like `tlsx` to return back a `client_cert_required` attribute to indicate whether or not the remote server requires clients to authenticate using a certificate.

### Describe the use case of this feature:
A common security practice when using third-party edge services like Cloudflare is to require mutual TLS between the edge service and the backend web servers to ensure that third-parties are not able to bypass the edge service and make requests to the web servers directly. In these cases, it is useful to be able to scan a particular set of endpoints to determine whether or not there are any that are missing this control that need to be remediated.

**Comment by GeorginaReeder** [comment]
Thanks for this feature request @mark-adams , we'll definitely take a look into it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!
