### ISSUE TITLE
false negative result - incorrectly states TLS version support

### ISSUE THREAD

**Issue by emgaurav** [projectdiscovery/tlsx#81]
### tlsx version: 
v0.0.6

### Current Behavior:

I am trying to check the version support for all my subdomains. There are few subdomains I know are running on TLS 1.1 and 1.0 but tlsx returns TLS1.2 on them when used via -sv flag.
testssl shows TLS1.0 is supported but tlsx does not. 

### Expected Behavior:

Minimum tls version supported should be shown correctly.

### Steps To Reproduce:
NA

**Comment by ehsandeep** [comment]
By default, tlsx displays what version is used for the connection, tls version enum can be done with `-ve` flag.
