### ISSUE TITLE
go install command does not download the current version.

### ISSUE THREAD

**Issue by kylojsja** [projectdiscovery/tlsx#89]
Hi team,
go install command does not download the current version.
example : 
go install github.com/projectdiscovery/tlsx/cmd/tlsx@latest
normally it should download the released version 0.0.7 but it downloads version 0.0.6.
I tested it on different devices and it won't download the latest version. can you please check?
Best Regards.

**Comment by ehsandeep** [comment]
@kylojsja it does download latest code, it's just the version number in banner were not updated in last release that is now fixed with https://github.com/projectdiscovery/tlsx/pull/91, thank you for pointing this out.
